name: postgresql
adopt-info: postgresql
base: core22
summary: PostgreSQL is a powerful, open source object-relational database system.
description: |
  PostgreSQL is a powerful, open source object-relational database system.
  It has more than 15 years of active development and a proven architecture
  that has earned it a strong reputation for reliability, data integrity,
  and correctness.

grade: stable
confinement: strict

license: "BSD-3-Clause AND CC-BY-SA-4.0 AND GPL-3.0-or-later"

# Minimum snapd version to support using setpriv from base snap
# https://github.com/canonical/snapd/commit/1792fa040db787d766098ba4238dbcfaddfe0f7e
assumes:
  - snapd2.68

architectures:
  - amd64
  - arm64
  - ppc64el
  - riscv64
  - s390x

# postgres hates to run with root permissions and this is a workaround to allow
# a snap to drop privileges to some non-root user.
# Requires setpriv and some sort of command chain script to handle permission
# dropping. See: https://snapcraft.io/docs/system-usernames
system-usernames:
  snap_daemon: shared

# This slot exposes all of this snap to any other snap to use postgresql without
# bundling any of postgresql. This allows multiple snaps to use the postgresql
# snap however they see fit, without duplicating postgresql files on the device
# (by bundling postgresql with every snap)
slots:
  postgresql:
    interface: content
    content: bins
    read:
      - $SNAP

hooks:
  install:
    plugs: &_plugs [network, network-bind]
    environment: &_env
      PATH:            "${SNAP}/usr/lib/postgresql/14/bin:$PATH"
      LD_LIBRARY_PATH: "${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$LD_LIBRARY_PATH"
      PERL5LIB:        "$PERL5LIB:$SNAP/usr/share/perl5:$SNAP/usr/share/perl"

apps:
  # This service manages postgres operations.
  postgresql:
    daemon: simple
    command: launch-postgresql start
    stop-command: launch-postgresql stop
    reload-command: launch-postgresql reload
    start-timeout: 10m
    plugs: *_plugs
    environment: *_env

  # This app is meant for debugging
  pgctl:
    command: pgctl-wrapper
    plugs: *_plugs
    environment: *_env

  # This app is meant for debugging
  psql:
    command: psql-wrapper
    plugs: *_plugs
    environment:
      <<: *_env
      PSQLRC: $SNAP_COMMON/.psqlrc

parts:
  postgresql:
    plugin: dump
    source: src/
    stage-packages:
      - perl
      - postgresql
      # Required for landscape
      # There's no good reason it should be here and not with landscape;
      # something to experiment with
      - postgresql-14-debversion
      - postgresql-plpython3-14
    override-build: |
      craftctl default

      craftctl set version=$(dpkg-deb -f "${CRAFT_PART_BUILD}/../stage_packages/postgresql_"*_all.deb Version)

  # Required by immich
  # There's no good reason it should be here and not with immich; something to
  # experiment with
  pgvector-rs:
    plugin: nil
    build-packages: [curl]
    # Within clang-16 this is a bit hairy
    override-build: |
      if [ "${CRAFT_ARCH_BUILD_FOR}" = "amd64" ] || [ "${CRAFT_ARCH_BUILD_FOR}" = "arm64" ]; then
        curl -fLo "vectors-pg14_0.2.1_${CRAFT_ARCH_BUILD_FOR}.deb" \
          "https://github.com/tensorchord/pgvecto.rs/releases/download/v0.2.1/vectors-pg14_0.2.1_${CRAFT_ARCH_BUILD_FOR}.deb"
        dpkg -x "vectors-pg14_0.2.1_${CRAFT_ARCH_BUILD_FOR}.deb" "${CRAFT_PART_INSTALL}/"
      fi
    stage:
      - -usr/share/doc
