name: postgresql
adopt-info: postgresql
base: core24
summary: PostgreSQL is a powerful, open source object-relational database system.
description: |
  PostgreSQL is a powerful, open source object-relational database system.
  It has more than 15 years of active development and a proven architecture
  that has earned it a strong reputation for reliability, data integrity,
  and correctness.

grade: stable
confinement: strict

license: "BSD-3-Clause AND CC-BY-SA-4.0 AND GPL-3.0-or-later"

# Minimum snapd version to support using setpriv from base snap
# https://github.com/canonical/snapd/commit/1792fa040db787d766098ba4238dbcfaddfe0f7e
assumes:
  - snapd2.68

platforms:
  amd64:
  arm64:
  armhf:
  s390x:
  ppc64el:
  # riscv64:

# postgres hates to run with root permissions and this is a workaround to allow
# a snap to drop privileges to some non-root user.
# Requires setpriv and some sort of command chain script to handle permission
# dropping. See: https://snapcraft.io/docs/system-usernames
system-usernames:
  snap_daemon: shared

apps:
  # This service manages postgres operations.
  postgresql:
    daemon: simple
    command: launch-postgresql start
    stop-command: launch-postgresql stop
    reload-command: launch-postgresql reload
    start-timeout: 10m
    install-mode: disable
    plugs: [network, network-bind]
    environment:
      PATH:     $SNAP/usr/lib/postgresql/16/bin:$PATH
      PERL5LIB: $PERL5LIB:$SNAP/usr/share/perl5:$SNAP/usr/share/perl

  # This app is meant for debugging
  pgctl:
    command: pgctl-wrapper
    plugs: [network, network-bind]
    environment:
      PATH:     $SNAP/usr/lib/postgresql/16/bin:$PATH
      PERL5LIB: $PERL5LIB:$SNAP/usr/share/perl5:$SNAP/usr/share/perl

  # This app is meant for debugging
  psql:
    command: psql-wrapper
    plugs: [network, network-bind]
    environment:
      PSQLRC:   $SNAP_COMMON/.psqlrc
      PATH:     $SNAP/usr/lib/postgresql/16/bin:$PATH
      PERL5LIB: $PERL5LIB:$SNAP/usr/share/perl5:$SNAP/usr/share/perl

# This slot exposes all of this snap to any other snap to use postgresql without
# bundling any of postgresql. This allows # multiple snaps to use the postgresql
# snap however they see fit, without duplicating postgresql files on the device
# (by bundling postgresql with every snap)
slots:
  postgresql:
    interface: content
    content: bins
    read:
      - .

parts:
  postgresql:
    plugin: dump
    source: src/
    stage-packages:
      - perl
      - postgresql
      # TODO: ship debversion as a component
      - postgresql-16-debversion
      - postgresql-plpython3-16
    override-build: |
      craftctl default

      craftctl set version=$(dpkg-deb -f "${CRAFT_PART_BUILD}/../stage_packages/postgresql_"*_all.deb Version)
