name: postgresql
adopt-info: postgresql
base: core24
summary: PostgreSQL is a powerful, open source object-relational database system.
description: |
  PostgreSQL is a powerful, open source object-relational database system.
  It has more than 15 years of active development and a proven architecture
  that has earned it a strong reputation for reliability, data integrity,
  and correctness.

grade: stable
confinement: strict

license: "BSD-3-Clause AND CC-BY-SA-4.0 AND GPL-3.0-or-later"

# Minimum snapd version to support using setpriv from base snap
# https://github.com/canonical/snapd/commit/1792fa040db787d766098ba4238dbcfaddfe0f7e
assumes:
  - snapd2.68

platforms:
  amd64:
  arm64:
  ppc64el:
  riscv64:
  s390x:

# postgres hates to run with root permissions and this is a workaround to allow
# a snap to drop privileges to some non-root user.
# Requires setpriv and some sort of command chain script to handle permission
# dropping. See: https://snapcraft.io/docs/system-usernames
system-usernames:
  snap_daemon: shared

# This slot exposes all of this snap to any other snap to use postgresql without
# bundling any of postgresql. This allows multiple snaps to use the postgresql
# snap however they see fit, without duplicating postgresql files on the device
# (by bundling postgresql with every snap)
slots:
  postgresql:
    interface: content
    content: bins
    read:
      - $SNAP

hooks:
  install:
    plugs: &_plugs [network, network-bind]
    environment: &_env
      PATH:            "${SNAP}/usr/lib/postgresql/16/bin:$PATH"
      LD_LIBRARY_PATH: "${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$LD_LIBRARY_PATH"
      PERL5LIB:        "$PERL5LIB:$SNAP/usr/share/perl5:$SNAP/usr/share/perl"

apps:
  # This service manages postgres operations.
  postgresql:
    daemon: simple
    command: launch-postgresql start
    stop-command: launch-postgresql stop
    reload-command: launch-postgresql reload
    start-timeout: 10m
    plugs: *_plugs
    environment: *_env

  # This app is meant for debugging
  pgctl:
    command: pgctl-wrapper
    plugs: *_plugs
    environment: *_env

  # This app is meant for debugging
  psql:
    command: psql-wrapper
    plugs: *_plugs
    environment:
      <<: *_env
      PSQLRC: $SNAP_COMMON/.psqlrc

parts:
  postgresql:
    plugin: dump
    source: src/
    stage-packages:
      - perl
      - postgresql
      # Required for landscape
      # There's no good reason it should be here and not with landscape;
      # something to experiment with
      - postgresql-16-debversion
      - postgresql-plpython3-16
    override-build: |
      craftctl default

      craftctl set version=$(dpkg-deb -f "${CRAFT_PART_BUILD}/../stage_packages/postgresql_"*_all.deb Version)

  # Required by immich
  # There's no good reason it should be here and not with immich; something to
  # experiment with
  pgvector-rs:
    plugin: rust
    source: https://github.com/tensorchord/pgvecto.rs
    source-depth: 1
    source-type: git
    source-tag: v0.2.0
    build-packages:
      - clang-16
      - libssl-dev
      - pkg-config
      - postgresql
      - postgresql-server-dev-16
    override-build: |
      cargo install \
        cargo-pgrx  \
        --locked    \
        --version $(grep 'pgrx = { version =' Cargo.toml | cut -d\" -f2)

      sed -i 's/version = "0.0.0"/version = "0.2.0"/' Cargo.toml

      cargo pgrx init    --pg16    pg_config
      cargo pgrx package --out-dir "${CRAFT_PART_INSTALL}/"
