#!/bin/sh -eux

# We only want the octal to apply to the last directory
# shellcheck disable=2174
mkdir -pm 0750 "${SNAP_COMMON}/logs" \
               "${SNAP_COMMON}/history" \
               "${SNAP_COMMON}/database" \
               "${SNAP_COMMON}/postgresql"

# postgres does not like being root. Satisfy it by dropping priv
# As a result, directory ownership must change
# References to setpriv-wrapper indicate when priveleges must be dropped
chown -Rf snap_daemon:snap_daemon "${SNAP_COMMON}/logs"
chown -Rf snap_daemon:snap_daemon "${SNAP_COMMON}/history"
chown -Rf snap_daemon:snap_daemon "${SNAP_COMMON}/database"
chown -Rf snap_daemon:snap_daemon "${SNAP_COMMON}/postgresql"

daemon="$(snapct get daemon)"
if [ "$daemon" = "true" ]; then
  snapctl start --enable "${SNAP_INSTANCE_NAME}.postgresql"
  # TODO: make database initialization configurable.
  # Create a cluster so that postgres is available immediately.
  initdb \
      --pgdata="${SNAP_COMMON}/database" \
      --username=admin                   \
      --no-instructions
fi
